// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: shopModel.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class CartStructProto;
@class CategoryStructProto;
@class OrderStructProto;
@class ProductStructProto;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - Enum MessageType

typedef GPB_ENUM(MessageType) {
  /**
   * Value used if any message's field encounters a value that is not defined
   * by this enum. The message will also have C functions to get/set the rawValue
   * of the field.
   **/
  MessageType_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
  MessageType_TMessageSucc = 0,
  MessageType_TMessageGetStorageFail = 1,
  MessageType_TMessageRegUserAlreadyExist = 2,
  MessageType_TMessageRegSetUserFail = 3,
  MessageType_TMessageRegSaddUserFail = 4,
  MessageType_TMessageLoginGetUserFail = 5,
  MessageType_TMessageLoginUserNotExist = 6,
  MessageType_TMessageLoginDecoderUserValueFail = 7,
  MessageType_TMessageLoginPasswordError = 8,
  MessageType_TMessageRegSisMemberFail = 9,
  MessageType_TMessageRegDecoderFail = 10,
  MessageType_TMessageLoginDecoderFail = 11,
  MessageType_TMessageAddProductDecoderFail = 12,
  MessageType_TMessageAddCategoryDecoderFail = 13,
  MessageType_TMessageAddCategorySisMemberFail = 14,
  MessageType_TMessageAddCategoryAlreadyExist = 15,
  MessageType_TMessageAddCategoryNameSaddFail = 16,
  MessageType_TMessageAddCategoryIdSaddFail = 17,
  MessageType_TMessageAddCategorySetIdFail = 18,
  MessageType_TMessageAddProductAlreadyExist = 19,
  MessageType_TMessageAddProductGetNameFail = 20,
  MessageType_TMessageAddCategorySetNameFail = 21,
  MessageType_TMessageAddProductSaddFail = 22,
  MessageType_TMessageAddProductSetIdFail = 23,
  MessageType_TMessageAddProductSetPacketFail = 24,
  MessageType_TMessageGetAllCategorySisMemberIdFail = 25,
  MessageType_TMessageGetAllCategorySisMemberNameFail = 26,
  MessageType_TMessageGetAllCategoryDecoderFail = 27,
  MessageType_TMessageGetAllCategoryIdNameLenNotMatch = 28,
  MessageType_TMesageGetProductByCategorySmemberFail = 29,
  MessageType_TMessageGetProductGetFail = 30,
  MessageType_TMessageGetProductByCategoryDecoderFail = 31,
  MessageType_TMessageReqArgsInvalid = 32,
  MessageType_TMessageGetProductByNameDecoderFail = 33,
  MessageType_TMessageFromStorageProductDecoderFail = 34,
  MessageType_TMessageGetProductGetIdFail = 35,
  MessageType_TMessageDelProductByNameProductNotExist = 36,
  MessageType_TMessageDelProductByNameGetProductFail = 37,
  MessageType_TMessageDelProductByNameDelProductNameKeyFail = 38,
  MessageType_TMessageDelProductByNameDelProductIdKeyFail = 39,
  MessageType_TMessageDelProductByNameDelIdFromTypeSetFail = 40,
  MessageType_TMessageDelProductByNameDecoderFail = 41,
};

GPBEnumDescriptor *MessageType_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL MessageType_IsValidValue(int32_t value);

#pragma mark - Enum ReqType

typedef GPB_ENUM(ReqType) {
  /**
   * Value used if any message's field encounters a value that is not defined
   * by this enum. The message will also have C functions to get/set the rawValue
   * of the field.
   **/
  ReqType_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
  ReqType_TReqTypeRegister = 0,
  ReqType_TReqTypeLogin = 1,
  ReqType_TReqTypeAddProduct = 2,
  ReqType_TReqTypeGetProductByName = 3,
  ReqType_TReqTypeGetProductByCategory = 4,
  ReqType_TReqTypeAddCategory = 5,
  ReqType_TReqTypeGetAllCategory = 6,
  ReqType_TReqTypeAddOrder = 7,
  ReqType_TReqTypeGetOrderById = 8,
  ReqType_TReqTypeGetOrderByUser = 9,
  ReqType_TReqTypeAddCart = 10,
  ReqType_TReqTypeGetCartById = 11,
  ReqType_TReqTypeGetCartByUser = 12,
  ReqType_TReqTypeDelProductByName = 13,
};

GPBEnumDescriptor *ReqType_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL ReqType_IsValidValue(int32_t value);

#pragma mark - Enum RspType

typedef GPB_ENUM(RspType) {
  /**
   * Value used if any message's field encounters a value that is not defined
   * by this enum. The message will also have C functions to get/set the rawValue
   * of the field.
   **/
  RspType_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
  RspType_TRspTypeRegister = 0,
  RspType_TRspTypeLogin = 1,
  RspType_TRspTypeAddProduct = 2,
  RspType_TRspTypeGetProductByName = 3,
  RspType_TRspTypeGetProductByCategory = 4,
  RspType_TRspTypeAddCategory = 5,
  RspType_TRspTypeGetAllCategory = 6,
  RspType_TRspTypeAddOrder = 7,
  RspType_TRspTypeGetOrderById = 8,
  RspType_TRspTypeGetOrderByUser = 9,
  RspType_TRspTypeAddCart = 10,
  RspType_TRspTypeGetCartById = 11,
  RspType_TRspTypeGetCartByUser = 12,
  RspType_TRspTypeDelProductByName = 13,
};

GPBEnumDescriptor *RspType_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL RspType_IsValidValue(int32_t value);

#pragma mark - ShopModelRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface ShopModelRoot : GPBRootObject
@end

#pragma mark - LoginProto

typedef GPB_ENUM(LoginProto_FieldNumber) {
  LoginProto_FieldNumber_Reqtype = 1,
  LoginProto_FieldNumber_Username = 2,
  LoginProto_FieldNumber_Password = 3,
  LoginProto_FieldNumber_Auth = 4,
};

@interface LoginProto : GPBMessage

@property(nonatomic, readwrite) ReqType reqtype;

@property(nonatomic, readwrite, copy, null_resettable) NSString *username;

@property(nonatomic, readwrite, copy, null_resettable) NSString *password;

@property(nonatomic, readwrite) int32_t auth;

@end

/**
 * Fetches the raw value of a @c LoginProto's @c reqtype property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t LoginProto_Reqtype_RawValue(LoginProto *message);
/**
 * Sets the raw value of an @c LoginProto's @c reqtype property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetLoginProto_Reqtype_RawValue(LoginProto *message, int32_t value);

#pragma mark - LoginRspProto

typedef GPB_ENUM(LoginRspProto_FieldNumber) {
  LoginRspProto_FieldNumber_Rspcode = 1,
  LoginRspProto_FieldNumber_Rsptype = 2,
  LoginRspProto_FieldNumber_Username = 3,
  LoginRspProto_FieldNumber_Rspmessage = 4,
};

@interface LoginRspProto : GPBMessage

@property(nonatomic, readwrite) MessageType rspcode;

@property(nonatomic, readwrite) RspType rsptype;

@property(nonatomic, readwrite, copy, null_resettable) NSString *username;

@property(nonatomic, readwrite, copy, null_resettable) NSString *rspmessage;

@end

/**
 * Fetches the raw value of a @c LoginRspProto's @c rspcode property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t LoginRspProto_Rspcode_RawValue(LoginRspProto *message);
/**
 * Sets the raw value of an @c LoginRspProto's @c rspcode property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetLoginRspProto_Rspcode_RawValue(LoginRspProto *message, int32_t value);

/**
 * Fetches the raw value of a @c LoginRspProto's @c rsptype property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t LoginRspProto_Rsptype_RawValue(LoginRspProto *message);
/**
 * Sets the raw value of an @c LoginRspProto's @c rsptype property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetLoginRspProto_Rsptype_RawValue(LoginRspProto *message, int32_t value);

#pragma mark - RegisterProto

typedef GPB_ENUM(RegisterProto_FieldNumber) {
  RegisterProto_FieldNumber_Reqtype = 1,
  RegisterProto_FieldNumber_Username = 2,
  RegisterProto_FieldNumber_Password = 3,
  RegisterProto_FieldNumber_Auth = 4,
};

@interface RegisterProto : GPBMessage

@property(nonatomic, readwrite) ReqType reqtype;

@property(nonatomic, readwrite, copy, null_resettable) NSString *username;

@property(nonatomic, readwrite, copy, null_resettable) NSString *password;

@property(nonatomic, readwrite) int32_t auth;

@end

/**
 * Fetches the raw value of a @c RegisterProto's @c reqtype property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t RegisterProto_Reqtype_RawValue(RegisterProto *message);
/**
 * Sets the raw value of an @c RegisterProto's @c reqtype property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetRegisterProto_Reqtype_RawValue(RegisterProto *message, int32_t value);

#pragma mark - RegisterRspProto

typedef GPB_ENUM(RegisterRspProto_FieldNumber) {
  RegisterRspProto_FieldNumber_Rspcode = 1,
  RegisterRspProto_FieldNumber_Rsptype = 2,
  RegisterRspProto_FieldNumber_Username = 3,
  RegisterRspProto_FieldNumber_Rspmessage = 4,
};

@interface RegisterRspProto : GPBMessage

@property(nonatomic, readwrite) MessageType rspcode;

@property(nonatomic, readwrite) RspType rsptype;

@property(nonatomic, readwrite, copy, null_resettable) NSString *username;

@property(nonatomic, readwrite, copy, null_resettable) NSString *rspmessage;

@end

/**
 * Fetches the raw value of a @c RegisterRspProto's @c rspcode property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t RegisterRspProto_Rspcode_RawValue(RegisterRspProto *message);
/**
 * Sets the raw value of an @c RegisterRspProto's @c rspcode property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetRegisterRspProto_Rspcode_RawValue(RegisterRspProto *message, int32_t value);

/**
 * Fetches the raw value of a @c RegisterRspProto's @c rsptype property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t RegisterRspProto_Rsptype_RawValue(RegisterRspProto *message);
/**
 * Sets the raw value of an @c RegisterRspProto's @c rsptype property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetRegisterRspProto_Rsptype_RawValue(RegisterRspProto *message, int32_t value);

#pragma mark - AddProductProto

typedef GPB_ENUM(AddProductProto_FieldNumber) {
  AddProductProto_FieldNumber_Reqtype = 1,
  AddProductProto_FieldNumber_Proname = 2,
  AddProductProto_FieldNumber_Price = 3,
  AddProductProto_FieldNumber_Picname = 4,
  AddProductProto_FieldNumber_Categoryid = 5,
};

@interface AddProductProto : GPBMessage

@property(nonatomic, readwrite) ReqType reqtype;

@property(nonatomic, readwrite, copy, null_resettable) NSString *proname;

@property(nonatomic, readwrite) float price;

@property(nonatomic, readwrite, copy, null_resettable) NSString *picname;

@property(nonatomic, readwrite, copy, null_resettable) NSString *categoryid;

@end

/**
 * Fetches the raw value of a @c AddProductProto's @c reqtype property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t AddProductProto_Reqtype_RawValue(AddProductProto *message);
/**
 * Sets the raw value of an @c AddProductProto's @c reqtype property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetAddProductProto_Reqtype_RawValue(AddProductProto *message, int32_t value);

#pragma mark - AddProductRspProto

typedef GPB_ENUM(AddProductRspProto_FieldNumber) {
  AddProductRspProto_FieldNumber_Rspcode = 1,
  AddProductRspProto_FieldNumber_Rspmessage = 2,
  AddProductRspProto_FieldNumber_Rsptype = 3,
  AddProductRspProto_FieldNumber_Proname = 4,
  AddProductRspProto_FieldNumber_Proid = 5,
  AddProductRspProto_FieldNumber_Categoryid = 6,
};

@interface AddProductRspProto : GPBMessage

@property(nonatomic, readwrite) MessageType rspcode;

@property(nonatomic, readwrite, copy, null_resettable) NSString *rspmessage;

@property(nonatomic, readwrite) RspType rsptype;

@property(nonatomic, readwrite, copy, null_resettable) NSString *proname;

@property(nonatomic, readwrite, copy, null_resettable) NSString *proid;

@property(nonatomic, readwrite, copy, null_resettable) NSString *categoryid;

@end

/**
 * Fetches the raw value of a @c AddProductRspProto's @c rspcode property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t AddProductRspProto_Rspcode_RawValue(AddProductRspProto *message);
/**
 * Sets the raw value of an @c AddProductRspProto's @c rspcode property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetAddProductRspProto_Rspcode_RawValue(AddProductRspProto *message, int32_t value);

/**
 * Fetches the raw value of a @c AddProductRspProto's @c rsptype property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t AddProductRspProto_Rsptype_RawValue(AddProductRspProto *message);
/**
 * Sets the raw value of an @c AddProductRspProto's @c rsptype property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetAddProductRspProto_Rsptype_RawValue(AddProductRspProto *message, int32_t value);

#pragma mark - GetProductByNameProto

typedef GPB_ENUM(GetProductByNameProto_FieldNumber) {
  GetProductByNameProto_FieldNumber_Proname = 1,
  GetProductByNameProto_FieldNumber_Reqtype = 2,
};

@interface GetProductByNameProto : GPBMessage

/** 商品名称 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *proname;

/** 请求类型 */
@property(nonatomic, readwrite) ReqType reqtype;

@end

/**
 * Fetches the raw value of a @c GetProductByNameProto's @c reqtype property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t GetProductByNameProto_Reqtype_RawValue(GetProductByNameProto *message);
/**
 * Sets the raw value of an @c GetProductByNameProto's @c reqtype property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetGetProductByNameProto_Reqtype_RawValue(GetProductByNameProto *message, int32_t value);

#pragma mark - GetProductByNameRspProto

typedef GPB_ENUM(GetProductByNameRspProto_FieldNumber) {
  GetProductByNameRspProto_FieldNumber_Proname = 1,
  GetProductByNameRspProto_FieldNumber_Price = 2,
  GetProductByNameRspProto_FieldNumber_Picname = 3,
  GetProductByNameRspProto_FieldNumber_Proid = 4,
  GetProductByNameRspProto_FieldNumber_Rspcode = 5,
  GetProductByNameRspProto_FieldNumber_Rsptype = 6,
  GetProductByNameRspProto_FieldNumber_Rspmessage = 7,
  GetProductByNameRspProto_FieldNumber_Categoryid = 8,
};

/**
 * 根据商品名称获取商品返回协议
 **/
@interface GetProductByNameRspProto : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *proname;

@property(nonatomic, readwrite) float price;

@property(nonatomic, readwrite, copy, null_resettable) NSString *picname;

@property(nonatomic, readwrite, copy, null_resettable) NSString *proid;

@property(nonatomic, readwrite) MessageType rspcode;

@property(nonatomic, readwrite) RspType rsptype;

@property(nonatomic, readwrite, copy, null_resettable) NSString *rspmessage;

@property(nonatomic, readwrite, copy, null_resettable) NSString *categoryid;

@end

/**
 * Fetches the raw value of a @c GetProductByNameRspProto's @c rspcode property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t GetProductByNameRspProto_Rspcode_RawValue(GetProductByNameRspProto *message);
/**
 * Sets the raw value of an @c GetProductByNameRspProto's @c rspcode property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetGetProductByNameRspProto_Rspcode_RawValue(GetProductByNameRspProto *message, int32_t value);

/**
 * Fetches the raw value of a @c GetProductByNameRspProto's @c rsptype property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t GetProductByNameRspProto_Rsptype_RawValue(GetProductByNameRspProto *message);
/**
 * Sets the raw value of an @c GetProductByNameRspProto's @c rsptype property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetGetProductByNameRspProto_Rsptype_RawValue(GetProductByNameRspProto *message, int32_t value);

#pragma mark - DelProductByNameProto

typedef GPB_ENUM(DelProductByNameProto_FieldNumber) {
  DelProductByNameProto_FieldNumber_Proname = 1,
  DelProductByNameProto_FieldNumber_Reqtype = 2,
};

@interface DelProductByNameProto : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *proname;

@property(nonatomic, readwrite) ReqType reqtype;

@end

/**
 * Fetches the raw value of a @c DelProductByNameProto's @c reqtype property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t DelProductByNameProto_Reqtype_RawValue(DelProductByNameProto *message);
/**
 * Sets the raw value of an @c DelProductByNameProto's @c reqtype property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetDelProductByNameProto_Reqtype_RawValue(DelProductByNameProto *message, int32_t value);

#pragma mark - DelProductByNameRspProto

typedef GPB_ENUM(DelProductByNameRspProto_FieldNumber) {
  DelProductByNameRspProto_FieldNumber_Proname = 1,
  DelProductByNameRspProto_FieldNumber_Proid = 2,
  DelProductByNameRspProto_FieldNumber_Rspcode = 3,
  DelProductByNameRspProto_FieldNumber_Rsptype = 4,
  DelProductByNameRspProto_FieldNumber_Rspmessage = 5,
};

@interface DelProductByNameRspProto : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *proname;

@property(nonatomic, readwrite, copy, null_resettable) NSString *proid;

@property(nonatomic, readwrite) MessageType rspcode;

@property(nonatomic, readwrite) RspType rsptype;

@property(nonatomic, readwrite, copy, null_resettable) NSString *rspmessage;

@end

/**
 * Fetches the raw value of a @c DelProductByNameRspProto's @c rspcode property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t DelProductByNameRspProto_Rspcode_RawValue(DelProductByNameRspProto *message);
/**
 * Sets the raw value of an @c DelProductByNameRspProto's @c rspcode property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetDelProductByNameRspProto_Rspcode_RawValue(DelProductByNameRspProto *message, int32_t value);

/**
 * Fetches the raw value of a @c DelProductByNameRspProto's @c rsptype property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t DelProductByNameRspProto_Rsptype_RawValue(DelProductByNameRspProto *message);
/**
 * Sets the raw value of an @c DelProductByNameRspProto's @c rsptype property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetDelProductByNameRspProto_Rsptype_RawValue(DelProductByNameRspProto *message, int32_t value);

#pragma mark - ProductStructProto

typedef GPB_ENUM(ProductStructProto_FieldNumber) {
  ProductStructProto_FieldNumber_Proid = 1,
  ProductStructProto_FieldNumber_Proname = 2,
  ProductStructProto_FieldNumber_Price = 4,
  ProductStructProto_FieldNumber_Picname = 5,
  ProductStructProto_FieldNumber_Categoryid = 6,
};

@interface ProductStructProto : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *proid;

@property(nonatomic, readwrite, copy, null_resettable) NSString *proname;

@property(nonatomic, readwrite) float price;

@property(nonatomic, readwrite, copy, null_resettable) NSString *picname;

@property(nonatomic, readwrite, copy, null_resettable) NSString *categoryid;

@end

#pragma mark - GetProductByCateGoryProto

typedef GPB_ENUM(GetProductByCateGoryProto_FieldNumber) {
  GetProductByCateGoryProto_FieldNumber_Categoryid = 1,
  GetProductByCateGoryProto_FieldNumber_Reqtype = 2,
};

@interface GetProductByCateGoryProto : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *categoryid;

@property(nonatomic, readwrite) ReqType reqtype;

@end

/**
 * Fetches the raw value of a @c GetProductByCateGoryProto's @c reqtype property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t GetProductByCateGoryProto_Reqtype_RawValue(GetProductByCateGoryProto *message);
/**
 * Sets the raw value of an @c GetProductByCateGoryProto's @c reqtype property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetGetProductByCateGoryProto_Reqtype_RawValue(GetProductByCateGoryProto *message, int32_t value);

#pragma mark - GetProductByCateGoryRspProto

typedef GPB_ENUM(GetProductByCateGoryRspProto_FieldNumber) {
  GetProductByCateGoryRspProto_FieldNumber_Rspcode = 1,
  GetProductByCateGoryRspProto_FieldNumber_Products = 2,
  GetProductByCateGoryRspProto_FieldNumber_Rsptype = 3,
  GetProductByCateGoryRspProto_FieldNumber_Rspmessage = 4,
};

@interface GetProductByCateGoryRspProto : GPBMessage

@property(nonatomic, readwrite) MessageType rspcode;

@property(nonatomic, readwrite, strong, null_resettable) ProductStructProto *products;
/** Test to see if @c products has been set. */
@property(nonatomic, readwrite) BOOL hasProducts;

@property(nonatomic, readwrite) RspType rsptype;

@property(nonatomic, readwrite, copy, null_resettable) NSString *rspmessage;

@end

/**
 * Fetches the raw value of a @c GetProductByCateGoryRspProto's @c rspcode property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t GetProductByCateGoryRspProto_Rspcode_RawValue(GetProductByCateGoryRspProto *message);
/**
 * Sets the raw value of an @c GetProductByCateGoryRspProto's @c rspcode property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetGetProductByCateGoryRspProto_Rspcode_RawValue(GetProductByCateGoryRspProto *message, int32_t value);

/**
 * Fetches the raw value of a @c GetProductByCateGoryRspProto's @c rsptype property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t GetProductByCateGoryRspProto_Rsptype_RawValue(GetProductByCateGoryRspProto *message);
/**
 * Sets the raw value of an @c GetProductByCateGoryRspProto's @c rsptype property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetGetProductByCateGoryRspProto_Rsptype_RawValue(GetProductByCateGoryRspProto *message, int32_t value);

#pragma mark - AddCategoryProto

typedef GPB_ENUM(AddCategoryProto_FieldNumber) {
  AddCategoryProto_FieldNumber_Categoryname = 1,
  AddCategoryProto_FieldNumber_Reqtype = 2,
  AddCategoryProto_FieldNumber_Picname = 3,
};

@interface AddCategoryProto : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *categoryname;

@property(nonatomic, readwrite) ReqType reqtype;

@property(nonatomic, readwrite, copy, null_resettable) NSString *picname;

@end

/**
 * Fetches the raw value of a @c AddCategoryProto's @c reqtype property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t AddCategoryProto_Reqtype_RawValue(AddCategoryProto *message);
/**
 * Sets the raw value of an @c AddCategoryProto's @c reqtype property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetAddCategoryProto_Reqtype_RawValue(AddCategoryProto *message, int32_t value);

#pragma mark - AddCategoryRspProto

typedef GPB_ENUM(AddCategoryRspProto_FieldNumber) {
  AddCategoryRspProto_FieldNumber_Categoryid = 1,
  AddCategoryRspProto_FieldNumber_Categoryname = 2,
  AddCategoryRspProto_FieldNumber_Rspcode = 3,
  AddCategoryRspProto_FieldNumber_Rsptype = 4,
  AddCategoryRspProto_FieldNumber_Rspmessage = 5,
};

@interface AddCategoryRspProto : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *categoryid;

@property(nonatomic, readwrite, copy, null_resettable) NSString *categoryname;

@property(nonatomic, readwrite) MessageType rspcode;

@property(nonatomic, readwrite) RspType rsptype;

@property(nonatomic, readwrite, copy, null_resettable) NSString *rspmessage;

@end

/**
 * Fetches the raw value of a @c AddCategoryRspProto's @c rspcode property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t AddCategoryRspProto_Rspcode_RawValue(AddCategoryRspProto *message);
/**
 * Sets the raw value of an @c AddCategoryRspProto's @c rspcode property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetAddCategoryRspProto_Rspcode_RawValue(AddCategoryRspProto *message, int32_t value);

/**
 * Fetches the raw value of a @c AddCategoryRspProto's @c rsptype property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t AddCategoryRspProto_Rsptype_RawValue(AddCategoryRspProto *message);
/**
 * Sets the raw value of an @c AddCategoryRspProto's @c rsptype property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetAddCategoryRspProto_Rsptype_RawValue(AddCategoryRspProto *message, int32_t value);

#pragma mark - CategoryStructProto

typedef GPB_ENUM(CategoryStructProto_FieldNumber) {
  CategoryStructProto_FieldNumber_Categoryid = 1,
  CategoryStructProto_FieldNumber_Categoryname = 2,
};

@interface CategoryStructProto : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *categoryid;

@property(nonatomic, readwrite, copy, null_resettable) NSString *categoryname;

@end

#pragma mark - GetAllCategoryProto

typedef GPB_ENUM(GetAllCategoryProto_FieldNumber) {
  GetAllCategoryProto_FieldNumber_Reqtype = 1,
};

@interface GetAllCategoryProto : GPBMessage

@property(nonatomic, readwrite) ReqType reqtype;

@end

/**
 * Fetches the raw value of a @c GetAllCategoryProto's @c reqtype property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t GetAllCategoryProto_Reqtype_RawValue(GetAllCategoryProto *message);
/**
 * Sets the raw value of an @c GetAllCategoryProto's @c reqtype property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetGetAllCategoryProto_Reqtype_RawValue(GetAllCategoryProto *message, int32_t value);

#pragma mark - GetAllCategoryRspProto

typedef GPB_ENUM(GetAllCategoryRspProto_FieldNumber) {
  GetAllCategoryRspProto_FieldNumber_Categories = 1,
  GetAllCategoryRspProto_FieldNumber_Rspcode = 2,
  GetAllCategoryRspProto_FieldNumber_Rsptype = 3,
  GetAllCategoryRspProto_FieldNumber_Rspmessage = 4,
};

@interface GetAllCategoryRspProto : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) CategoryStructProto *categories;
/** Test to see if @c categories has been set. */
@property(nonatomic, readwrite) BOOL hasCategories;

@property(nonatomic, readwrite) MessageType rspcode;

@property(nonatomic, readwrite) RspType rsptype;

@property(nonatomic, readwrite, copy, null_resettable) NSString *rspmessage;

@end

/**
 * Fetches the raw value of a @c GetAllCategoryRspProto's @c rspcode property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t GetAllCategoryRspProto_Rspcode_RawValue(GetAllCategoryRspProto *message);
/**
 * Sets the raw value of an @c GetAllCategoryRspProto's @c rspcode property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetGetAllCategoryRspProto_Rspcode_RawValue(GetAllCategoryRspProto *message, int32_t value);

/**
 * Fetches the raw value of a @c GetAllCategoryRspProto's @c rsptype property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t GetAllCategoryRspProto_Rsptype_RawValue(GetAllCategoryRspProto *message);
/**
 * Sets the raw value of an @c GetAllCategoryRspProto's @c rsptype property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetGetAllCategoryRspProto_Rsptype_RawValue(GetAllCategoryRspProto *message, int32_t value);

#pragma mark - AddOrderProto

typedef GPB_ENUM(AddOrderProto_FieldNumber) {
  AddOrderProto_FieldNumber_Username = 1,
  AddOrderProto_FieldNumber_Amounts = 2,
  AddOrderProto_FieldNumber_Proid = 3,
  AddOrderProto_FieldNumber_Proname = 4,
  AddOrderProto_FieldNumber_Totprice = 5,
  AddOrderProto_FieldNumber_Reqtype = 6,
};

@interface AddOrderProto : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *username;

@property(nonatomic, readwrite) float amounts;

@property(nonatomic, readwrite, copy, null_resettable) NSString *proid;

@property(nonatomic, readwrite, copy, null_resettable) NSString *proname;

@property(nonatomic, readwrite) float totprice;

@property(nonatomic, readwrite) ReqType reqtype;

@end

/**
 * Fetches the raw value of a @c AddOrderProto's @c reqtype property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t AddOrderProto_Reqtype_RawValue(AddOrderProto *message);
/**
 * Sets the raw value of an @c AddOrderProto's @c reqtype property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetAddOrderProto_Reqtype_RawValue(AddOrderProto *message, int32_t value);

#pragma mark - AddOrderRspProto

typedef GPB_ENUM(AddOrderRspProto_FieldNumber) {
  AddOrderRspProto_FieldNumber_Orderid = 1,
  AddOrderRspProto_FieldNumber_Username = 2,
  AddOrderRspProto_FieldNumber_Rspcode = 3,
  AddOrderRspProto_FieldNumber_Rsptype = 4,
};

@interface AddOrderRspProto : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *orderid;

@property(nonatomic, readwrite, copy, null_resettable) NSString *username;

@property(nonatomic, readwrite) MessageType rspcode;

@property(nonatomic, readwrite) RspType rsptype;

@end

/**
 * Fetches the raw value of a @c AddOrderRspProto's @c rspcode property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t AddOrderRspProto_Rspcode_RawValue(AddOrderRspProto *message);
/**
 * Sets the raw value of an @c AddOrderRspProto's @c rspcode property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetAddOrderRspProto_Rspcode_RawValue(AddOrderRspProto *message, int32_t value);

/**
 * Fetches the raw value of a @c AddOrderRspProto's @c rsptype property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t AddOrderRspProto_Rsptype_RawValue(AddOrderRspProto *message);
/**
 * Sets the raw value of an @c AddOrderRspProto's @c rsptype property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetAddOrderRspProto_Rsptype_RawValue(AddOrderRspProto *message, int32_t value);

#pragma mark - GetOrderByUserProto

typedef GPB_ENUM(GetOrderByUserProto_FieldNumber) {
  GetOrderByUserProto_FieldNumber_Username = 1,
  GetOrderByUserProto_FieldNumber_Reqtype = 2,
};

@interface GetOrderByUserProto : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *username;

@property(nonatomic, readwrite) ReqType reqtype;

@end

/**
 * Fetches the raw value of a @c GetOrderByUserProto's @c reqtype property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t GetOrderByUserProto_Reqtype_RawValue(GetOrderByUserProto *message);
/**
 * Sets the raw value of an @c GetOrderByUserProto's @c reqtype property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetGetOrderByUserProto_Reqtype_RawValue(GetOrderByUserProto *message, int32_t value);

#pragma mark - OrderStructProto

typedef GPB_ENUM(OrderStructProto_FieldNumber) {
  OrderStructProto_FieldNumber_Orderid = 1,
  OrderStructProto_FieldNumber_Username = 2,
  OrderStructProto_FieldNumber_Amounts = 3,
  OrderStructProto_FieldNumber_Totprice = 4,
  OrderStructProto_FieldNumber_Proid = 5,
  OrderStructProto_FieldNumber_Proname = 6,
};

@interface OrderStructProto : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *orderid;

@property(nonatomic, readwrite, copy, null_resettable) NSString *username;

@property(nonatomic, readwrite) float amounts;

@property(nonatomic, readwrite) float totprice;

@property(nonatomic, readwrite, copy, null_resettable) NSString *proid;

@property(nonatomic, readwrite, copy, null_resettable) NSString *proname;

@end

#pragma mark - GetOrderByUserRspProto

typedef GPB_ENUM(GetOrderByUserRspProto_FieldNumber) {
  GetOrderByUserRspProto_FieldNumber_Username = 1,
  GetOrderByUserRspProto_FieldNumber_Orders = 2,
  GetOrderByUserRspProto_FieldNumber_Rspcode = 3,
  GetOrderByUserRspProto_FieldNumber_Rsptype = 4,
};

@interface GetOrderByUserRspProto : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *username;

@property(nonatomic, readwrite, strong, null_resettable) OrderStructProto *orders;
/** Test to see if @c orders has been set. */
@property(nonatomic, readwrite) BOOL hasOrders;

@property(nonatomic, readwrite) MessageType rspcode;

@property(nonatomic, readwrite) RspType rsptype;

@end

/**
 * Fetches the raw value of a @c GetOrderByUserRspProto's @c rspcode property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t GetOrderByUserRspProto_Rspcode_RawValue(GetOrderByUserRspProto *message);
/**
 * Sets the raw value of an @c GetOrderByUserRspProto's @c rspcode property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetGetOrderByUserRspProto_Rspcode_RawValue(GetOrderByUserRspProto *message, int32_t value);

/**
 * Fetches the raw value of a @c GetOrderByUserRspProto's @c rsptype property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t GetOrderByUserRspProto_Rsptype_RawValue(GetOrderByUserRspProto *message);
/**
 * Sets the raw value of an @c GetOrderByUserRspProto's @c rsptype property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetGetOrderByUserRspProto_Rsptype_RawValue(GetOrderByUserRspProto *message, int32_t value);

#pragma mark - GetOrderByIdProto

typedef GPB_ENUM(GetOrderByIdProto_FieldNumber) {
  GetOrderByIdProto_FieldNumber_Orderid = 1,
  GetOrderByIdProto_FieldNumber_Reqtype = 2,
};

@interface GetOrderByIdProto : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *orderid;

@property(nonatomic, readwrite) ReqType reqtype;

@end

/**
 * Fetches the raw value of a @c GetOrderByIdProto's @c reqtype property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t GetOrderByIdProto_Reqtype_RawValue(GetOrderByIdProto *message);
/**
 * Sets the raw value of an @c GetOrderByIdProto's @c reqtype property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetGetOrderByIdProto_Reqtype_RawValue(GetOrderByIdProto *message, int32_t value);

#pragma mark - GetOrderByIdRspProto

typedef GPB_ENUM(GetOrderByIdRspProto_FieldNumber) {
  GetOrderByIdRspProto_FieldNumber_Orderid = 1,
  GetOrderByIdRspProto_FieldNumber_Order = 2,
  GetOrderByIdRspProto_FieldNumber_Rspcode = 3,
  GetOrderByIdRspProto_FieldNumber_Rsptype = 4,
};

@interface GetOrderByIdRspProto : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *orderid;

@property(nonatomic, readwrite, strong, null_resettable) OrderStructProto *order;
/** Test to see if @c order has been set. */
@property(nonatomic, readwrite) BOOL hasOrder;

@property(nonatomic, readwrite) MessageType rspcode;

@property(nonatomic, readwrite) RspType rsptype;

@end

/**
 * Fetches the raw value of a @c GetOrderByIdRspProto's @c rspcode property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t GetOrderByIdRspProto_Rspcode_RawValue(GetOrderByIdRspProto *message);
/**
 * Sets the raw value of an @c GetOrderByIdRspProto's @c rspcode property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetGetOrderByIdRspProto_Rspcode_RawValue(GetOrderByIdRspProto *message, int32_t value);

/**
 * Fetches the raw value of a @c GetOrderByIdRspProto's @c rsptype property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t GetOrderByIdRspProto_Rsptype_RawValue(GetOrderByIdRspProto *message);
/**
 * Sets the raw value of an @c GetOrderByIdRspProto's @c rsptype property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetGetOrderByIdRspProto_Rsptype_RawValue(GetOrderByIdRspProto *message, int32_t value);

#pragma mark - AddCartProto

typedef GPB_ENUM(AddCartProto_FieldNumber) {
  AddCartProto_FieldNumber_Username = 1,
  AddCartProto_FieldNumber_Amounts = 2,
  AddCartProto_FieldNumber_Proid = 3,
  AddCartProto_FieldNumber_Proname = 4,
  AddCartProto_FieldNumber_Reqtype = 5,
};

@interface AddCartProto : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *username;

@property(nonatomic, readwrite) float amounts;

@property(nonatomic, readwrite, copy, null_resettable) NSString *proid;

@property(nonatomic, readwrite, copy, null_resettable) NSString *proname;

@property(nonatomic, readwrite) ReqType reqtype;

@end

/**
 * Fetches the raw value of a @c AddCartProto's @c reqtype property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t AddCartProto_Reqtype_RawValue(AddCartProto *message);
/**
 * Sets the raw value of an @c AddCartProto's @c reqtype property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetAddCartProto_Reqtype_RawValue(AddCartProto *message, int32_t value);

#pragma mark - AddCartRspProto

typedef GPB_ENUM(AddCartRspProto_FieldNumber) {
  AddCartRspProto_FieldNumber_Cartid = 1,
  AddCartRspProto_FieldNumber_Username = 2,
  AddCartRspProto_FieldNumber_Rspcode = 3,
  AddCartRspProto_FieldNumber_Rsptype = 4,
};

@interface AddCartRspProto : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *cartid;

@property(nonatomic, readwrite, copy, null_resettable) NSString *username;

@property(nonatomic, readwrite) MessageType rspcode;

@property(nonatomic, readwrite) RspType rsptype;

@end

/**
 * Fetches the raw value of a @c AddCartRspProto's @c rspcode property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t AddCartRspProto_Rspcode_RawValue(AddCartRspProto *message);
/**
 * Sets the raw value of an @c AddCartRspProto's @c rspcode property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetAddCartRspProto_Rspcode_RawValue(AddCartRspProto *message, int32_t value);

/**
 * Fetches the raw value of a @c AddCartRspProto's @c rsptype property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t AddCartRspProto_Rsptype_RawValue(AddCartRspProto *message);
/**
 * Sets the raw value of an @c AddCartRspProto's @c rsptype property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetAddCartRspProto_Rsptype_RawValue(AddCartRspProto *message, int32_t value);

#pragma mark - CartStructProto

typedef GPB_ENUM(CartStructProto_FieldNumber) {
  CartStructProto_FieldNumber_Cartid = 1,
  CartStructProto_FieldNumber_Username = 2,
  CartStructProto_FieldNumber_Proname = 3,
  CartStructProto_FieldNumber_Proid = 4,
  CartStructProto_FieldNumber_Amounts = 5,
};

@interface CartStructProto : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *cartid;

@property(nonatomic, readwrite, copy, null_resettable) NSString *username;

@property(nonatomic, readwrite, copy, null_resettable) NSString *proname;

@property(nonatomic, readwrite, copy, null_resettable) NSString *proid;

@property(nonatomic, readwrite, copy, null_resettable) NSString *amounts;

@end

#pragma mark - GetCartByUserProto

typedef GPB_ENUM(GetCartByUserProto_FieldNumber) {
  GetCartByUserProto_FieldNumber_Username = 1,
  GetCartByUserProto_FieldNumber_Reqtype = 2,
};

@interface GetCartByUserProto : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *username;

@property(nonatomic, readwrite) ReqType reqtype;

@end

/**
 * Fetches the raw value of a @c GetCartByUserProto's @c reqtype property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t GetCartByUserProto_Reqtype_RawValue(GetCartByUserProto *message);
/**
 * Sets the raw value of an @c GetCartByUserProto's @c reqtype property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetGetCartByUserProto_Reqtype_RawValue(GetCartByUserProto *message, int32_t value);

#pragma mark - GetCartByUserRspProto

typedef GPB_ENUM(GetCartByUserRspProto_FieldNumber) {
  GetCartByUserRspProto_FieldNumber_Username = 1,
  GetCartByUserRspProto_FieldNumber_Rspcode = 2,
  GetCartByUserRspProto_FieldNumber_Carts = 3,
  GetCartByUserRspProto_FieldNumber_Rsptype = 4,
};

@interface GetCartByUserRspProto : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *username;

@property(nonatomic, readwrite) MessageType rspcode;

@property(nonatomic, readwrite, strong, null_resettable) CartStructProto *carts;
/** Test to see if @c carts has been set. */
@property(nonatomic, readwrite) BOOL hasCarts;

@property(nonatomic, readwrite) RspType rsptype;

@end

/**
 * Fetches the raw value of a @c GetCartByUserRspProto's @c rspcode property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t GetCartByUserRspProto_Rspcode_RawValue(GetCartByUserRspProto *message);
/**
 * Sets the raw value of an @c GetCartByUserRspProto's @c rspcode property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetGetCartByUserRspProto_Rspcode_RawValue(GetCartByUserRspProto *message, int32_t value);

/**
 * Fetches the raw value of a @c GetCartByUserRspProto's @c rsptype property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t GetCartByUserRspProto_Rsptype_RawValue(GetCartByUserRspProto *message);
/**
 * Sets the raw value of an @c GetCartByUserRspProto's @c rsptype property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetGetCartByUserRspProto_Rsptype_RawValue(GetCartByUserRspProto *message, int32_t value);

#pragma mark - GetCartByIdProto

typedef GPB_ENUM(GetCartByIdProto_FieldNumber) {
  GetCartByIdProto_FieldNumber_Cartid = 1,
  GetCartByIdProto_FieldNumber_Reqtype = 2,
};

@interface GetCartByIdProto : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *cartid;

@property(nonatomic, readwrite) ReqType reqtype;

@end

/**
 * Fetches the raw value of a @c GetCartByIdProto's @c reqtype property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t GetCartByIdProto_Reqtype_RawValue(GetCartByIdProto *message);
/**
 * Sets the raw value of an @c GetCartByIdProto's @c reqtype property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetGetCartByIdProto_Reqtype_RawValue(GetCartByIdProto *message, int32_t value);

#pragma mark - GetCartByIdRspProto

typedef GPB_ENUM(GetCartByIdRspProto_FieldNumber) {
  GetCartByIdRspProto_FieldNumber_Cartid = 1,
  GetCartByIdRspProto_FieldNumber_Rspcode = 2,
  GetCartByIdRspProto_FieldNumber_Cart = 3,
  GetCartByIdRspProto_FieldNumber_Rsptype = 4,
};

@interface GetCartByIdRspProto : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *cartid;

@property(nonatomic, readwrite) MessageType rspcode;

@property(nonatomic, readwrite, strong, null_resettable) CartStructProto *cart;
/** Test to see if @c cart has been set. */
@property(nonatomic, readwrite) BOOL hasCart;

@property(nonatomic, readwrite) RspType rsptype;

@end

/**
 * Fetches the raw value of a @c GetCartByIdRspProto's @c rspcode property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t GetCartByIdRspProto_Rspcode_RawValue(GetCartByIdRspProto *message);
/**
 * Sets the raw value of an @c GetCartByIdRspProto's @c rspcode property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetGetCartByIdRspProto_Rspcode_RawValue(GetCartByIdRspProto *message, int32_t value);

/**
 * Fetches the raw value of a @c GetCartByIdRspProto's @c rsptype property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t GetCartByIdRspProto_Rsptype_RawValue(GetCartByIdRspProto *message);
/**
 * Sets the raw value of an @c GetCartByIdRspProto's @c rsptype property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetGetCartByIdRspProto_Rsptype_RawValue(GetCartByIdRspProto *message, int32_t value);

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
